### ISSUE TITLE
Cannot UPDATE or DELETE from subquery

### ISSUE THREAD

**Issue by jutxle** [tombrothers/VfpEntityFrameworkProvider2#1]
Currently our team cannot save changes to free tables.  We followed the guide to setting up a candidate keys which resolved the first exception we were getting, but now any updates we attempt result in {"SQL: Cannot UPDATE or DELETE from subquery."} despite the fact that we are not performing any subqueries

**Comment by tombrothers** [comment]
My guess is that you created your Entity Model prior to adding the candidate keys and that you are using Entity Framework in a way that creates an Edmx file.  If that is the case you probably just need to recreate your Entity Model so that the new Edmx file is aware of the candidate key.

If that is not the case, could you send me an example project for me to research this issue? (tombrothers@outlook.com)
