### ISSUE TITLE
Query retrieves entire table

### ISSUE THREAD

**Issue by rasputino** [tombrothers/VfpEntityFrameworkProvider2#9]
I have a question, with any query like:

```
var model = new Model.Model();
var query = model.Table.Where(x => x.Id == "1");
var result = query.ToList();
```

The query retrieves all the table data, I monitored it with a network analyzer. The .dbf table has 100MB... but we only want one record. Is this a normal behavior of the vfp provider?

**Comment by mPisano** [comment]
I believe you are seeing this because its not using the indexes.
Double check your CDX tags that Id had an index.
Also 
VFP introduced in 9.1 different sort orders based on the CodePage of the table and if they are not the same as the OleDbProvider then "Rushmore" (the autoselection on indexs) is disabled.

Make sure your connection string specifies Codepage and they Match the table in VFP (use DISP STAT)

<add name="FoxDbContext" providerName="VfpEntityFrameworkProvider2" connectionString="data source={0};deleted=True;null=False;enginebehavior=90;CODEPAGE=1252" />

If that doesn't do it maybe Tom has a better suggestion, but I can tell you that I use this provider and it works

HTH
Mike Pisano

**Comment by rasputino** [comment]
Thanks for the quickness.

The .dbf is on a network location (UNC). That Id has an index (sorry, is not really an Id is a column, but not the primary key). I checked the CodePage of the indexes because we're using FoxPro 9.1 and I added ";collating sequence=SPANISH" to the connection string, but that doesn't fix it.

I'll check it several times and you'll have news from me here.

Thanks for your help.

**Comment by tombrothers** [comment]
Try [turning on tracing](https://randomdevnotes.com/2013/06/02/identify-production-issues-using-vfpcommand-tracing/) to see if you can figure out the issue by looking at the generated sql statement.

**Comment by mPisano** [comment]
collating sequence=SPANISH"

That doesn't look correct - it's normally a number

USE Table
DISP STAT
to see codepage of table
Else
connectionString="data source={0};deleted=True;null=False;enginebehavior=90;CODEPAGE=1252"

Try Setting enginebehavior=80

Mike

**Comment by rasputino** [comment]
Hi, I did what you say, but finally, after many debugging, I concluded that "collating sequence=SPANISH" solves my problem, my indices where defined in SPANISH and after that change they started to work better.

Thanks for your help!

**Comment by mPisano** [comment]
If Collating Sequence works then great, I just hope it's consistent and your not seeing some sort of caching.  

As part of my normal conversion from FoxDos\VFP tables I always use CPZERO.prg and set them to a number (1252) and confirm it with "DISP STAT" in VFP and make sure the Connection String matches.

I'm not sure how the underlying provider maps "collating sequence" to "Codepage"...  Collating sequence from what I remember was from the older ODBC times and not OleDB.

http://fox.wikis.com/wc.dll?Wiki~VFP9RushmoreAndCodepage

Good Luck,
Mike
